version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4527:4527"
    environment:
      - ENV=production
      - PORT=4527
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4527/api/v1/regex"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s